[package]
name = "atsamd-usb-uart"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Using bbqueue because it gives a low-cost method to attempt a USB write,
# without removing data from the structure
bbqueue = {version = "0.4.12", features = ["thumbv6"]}

# TODO Remove defmt before publishing?
defmt = "0.2.0"
defmt-rtt = "0.2.0"

usb-device = "0.2.7"
usbd-serial = "0.1.1"
nb = "0.1.2"

[dependencies.atsamd-hal]
# Under-development version
default-features = false
# git = "https://github.com/ianrrees/atsamd"
# branch = "for-work"
path = '/home/irees/Projects/20201112 - atsamd-rs/atsamd-rs/hal'

[features]
default = [
    "defmt-default",
]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []