[package]
name = "atsamd-usb-uart"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# embedded-hal = "0.2.2"
usb-device = "0.2.7"
usbd-serial = "0.1.1"
nb = "0.1.2"

[dependencies.atsamd-hal]
# Under-development version
default-features = false
# git = "https://github.com/ianrrees/atsamd"
# branch = "for-work"
path = '/home/irees/Projects/20201112 - atsamd-rs/atsamd-rs/hal'